// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function ChooseFscanFile():Promise<string>;

export function ChooseOutputPath():Promise<string>;

export function GetDefaults():Promise<app.ScanRequest>;

export function GetScanState(arg1:string):Promise<app.ScanJobState>;

export function GetSupportedDatabaseTypes():Promise<Array<string>>;

export function OpenOutputFolder(arg1:string):Promise<void>;

export function ParseFscanFile(arg1:string):Promise<app.FscanPreview>;

export function ParseFscanText(arg1:string):Promise<app.FscanPreview>;

export function RunCustomSQL(arg1:app.ScanRequest):Promise<app.CustomSQLResult>;

export function StartScan(arg1:app.ScanRequest):Promise<app.ScanJobState>;

export function StopScan(arg1:string):Promise<app.ScanJobState>;
