// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app, main} from '../models';

export function ChooseFscanFile():Promise<string>;

export function ChooseOutputPath():Promise<string>;

export function CreateTask(arg1:any):Promise<any>;

export function DeleteTask(arg1:string):Promise<void>;

export function GetDefaults():Promise<app.ScanRequest>;

export function GetScanState(arg1:string):Promise<app.ScanJobState>;

export function GetSupportedDatabaseTypes():Promise<Array<string>>;

export function GetTask(arg1:string):Promise<any>;

export function GetTaskState(arg1:string):Promise<app.ScanJobState>;

export function GetVaultStatus():Promise<main.VaultStatus>;

export function ListTasks():Promise<any>;

export function OpenOutputFolder(arg1:string):Promise<void>;

export function ParseFscanFile(arg1:string):Promise<app.FscanPreview>;

export function ParseFscanText(arg1:string):Promise<app.FscanPreview>;

export function RunCustomSQL(arg1:app.ScanRequest):Promise<app.CustomSQLResult>;

export function RunTaskSQL(arg1:string):Promise<any>;

export function ResetVault():Promise<main.VaultStatus>;

export function SetupVault(arg1:string):Promise<main.VaultStatus>;

export function StartScan(arg1:app.ScanRequest):Promise<app.ScanJobState>;

export function StartTask(arg1:string):Promise<any>;

export function StopScan(arg1:string):Promise<app.ScanJobState>;

export function StopTask(arg1:string):Promise<any>;

export function TestConnection(arg1:app.ScanRequest):Promise<app.ConnectionTestResult>;

export function UnlockVault(arg1:string):Promise<main.VaultStatus>;

export function UpdateTask(arg1:any):Promise<any>;
