// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {app} from '../models';

export function ChooseBackupExportPath():Promise<string>;

export function ChooseBackupImportFile():Promise<string>;

export function ChooseFscanFile():Promise<string>;

export function ChooseOutputPath():Promise<string>;

export function CreateTask(arg1:main.CreateTaskRequest):Promise<main.GUITask>;

export function DeleteTask(arg1:string):Promise<void>;

export function ExportDataBackup(arg1:main.BackupExportRequest):Promise<main.BackupResult>;

export function GetDefaults():Promise<app.ScanRequest>;

export function GetScanState(arg1:string):Promise<app.ScanJobState>;

export function GetSupportedDatabaseTypes():Promise<Array<string>>;

export function GetTask(arg1:string):Promise<main.GUITask>;

export function GetTaskState(arg1:string):Promise<app.ScanJobState>;

export function GetVaultStatus():Promise<main.VaultStatus>;

export function ImportDataBackup(arg1:main.BackupImportRequest):Promise<main.BackupResult>;

export function ListTasks():Promise<Array<main.GUITask>>;

export function OpenOutputFolder(arg1:string):Promise<void>;

export function ParseFscanFile(arg1:string):Promise<app.FscanPreview>;

export function ParseFscanText(arg1:string):Promise<app.FscanPreview>;

export function ResetVault():Promise<main.VaultStatus>;

export function RunCustomSQL(arg1:app.ScanRequest):Promise<app.CustomSQLResult>;

export function RunTaskSQL(arg1:string):Promise<main.GUITask>;

export function SetupVault(arg1:string):Promise<main.VaultStatus>;

export function StartScan(arg1:app.ScanRequest):Promise<app.ScanJobState>;

export function StartTask(arg1:string):Promise<main.GUITask>;

export function StopScan(arg1:string):Promise<app.ScanJobState>;

export function StopTask(arg1:string):Promise<main.GUITask>;

export function TestConnection(arg1:app.ScanRequest):Promise<app.ConnectionTestResult>;

export function UnlockVault(arg1:string):Promise<main.VaultStatus>;

export function UpdateTask(arg1:main.UpdateTaskRequest):Promise<main.GUITask>;
