// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseBackupExportPath() {
  return window['go']['main']['App']['ChooseBackupExportPath']();
}

export function ChooseBackupImportFile() {
  return window['go']['main']['App']['ChooseBackupImportFile']();
}

export function ChooseFscanFile() {
  return window['go']['main']['App']['ChooseFscanFile']();
}

export function ChooseOutputPath() {
  return window['go']['main']['App']['ChooseOutputPath']();
}

export function CreateTask(arg1) {
  return window['go']['main']['App']['CreateTask'](arg1);
}

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function ExportDataBackup(arg1) {
  return window['go']['main']['App']['ExportDataBackup'](arg1);
}

export function GetDefaults() {
  return window['go']['main']['App']['GetDefaults']();
}

export function GetScanState(arg1) {
  return window['go']['main']['App']['GetScanState'](arg1);
}

export function GetSupportedDatabaseTypes() {
  return window['go']['main']['App']['GetSupportedDatabaseTypes']();
}

export function GetTask(arg1) {
  return window['go']['main']['App']['GetTask'](arg1);
}

export function GetTaskState(arg1) {
  return window['go']['main']['App']['GetTaskState'](arg1);
}

export function GetVaultStatus() {
  return window['go']['main']['App']['GetVaultStatus']();
}

export function ImportDataBackup(arg1) {
  return window['go']['main']['App']['ImportDataBackup'](arg1);
}

export function ListTasks() {
  return window['go']['main']['App']['ListTasks']();
}

export function OpenOutputFolder(arg1) {
  return window['go']['main']['App']['OpenOutputFolder'](arg1);
}

export function ParseFscanFile(arg1) {
  return window['go']['main']['App']['ParseFscanFile'](arg1);
}

export function ParseFscanText(arg1) {
  return window['go']['main']['App']['ParseFscanText'](arg1);
}

export function ResetVault() {
  return window['go']['main']['App']['ResetVault']();
}

export function RunCustomSQL(arg1) {
  return window['go']['main']['App']['RunCustomSQL'](arg1);
}

export function RunTaskSQL(arg1) {
  return window['go']['main']['App']['RunTaskSQL'](arg1);
}

export function SetupVault(arg1) {
  return window['go']['main']['App']['SetupVault'](arg1);
}

export function StartScan(arg1) {
  return window['go']['main']['App']['StartScan'](arg1);
}

export function StartTask(arg1) {
  return window['go']['main']['App']['StartTask'](arg1);
}

export function StopScan(arg1) {
  return window['go']['main']['App']['StopScan'](arg1);
}

export function StopTask(arg1) {
  return window['go']['main']['App']['StopTask'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}

export function UnlockVault(arg1) {
  return window['go']['main']['App']['UnlockVault'](arg1);
}

export function UpdateTask(arg1) {
  return window['go']['main']['App']['UpdateTask'](arg1);
}
