// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseFscanFile() {
  return window['go']['main']['App']['ChooseFscanFile']();
}

export function ChooseOutputPath() {
  return window['go']['main']['App']['ChooseOutputPath']();
}

export function GetDefaults() {
  return window['go']['main']['App']['GetDefaults']();
}

export function GetScanState(arg1) {
  return window['go']['main']['App']['GetScanState'](arg1);
}

export function GetSupportedDatabaseTypes() {
  return window['go']['main']['App']['GetSupportedDatabaseTypes']();
}

export function OpenOutputFolder(arg1) {
  return window['go']['main']['App']['OpenOutputFolder'](arg1);
}

export function ParseFscanFile(arg1) {
  return window['go']['main']['App']['ParseFscanFile'](arg1);
}

export function ParseFscanText(arg1) {
  return window['go']['main']['App']['ParseFscanText'](arg1);
}

export function RunCustomSQL(arg1) {
  return window['go']['main']['App']['RunCustomSQL'](arg1);
}

export function StartScan(arg1) {
  return window['go']['main']['App']['StartScan'](arg1);
}

export function StopScan(arg1) {
  return window['go']['main']['App']['StopScan'](arg1);
}
